### ISSUE TITLE
Some mods aren't here

### ISSUE THREAD

**Issue by cazpj** [skywardmc/adrenaline#25]
Why not include:
- LazyDFU;
- Starlight;
- Krypton;
- C2ME;
- Fastload;
- Language Reload;
- Very Many Players;
- Exordium;
- FastQuit;
- Noxesium;
- FastAnim;
- ServerCore;
- Let Me Despawn;
- Clumps;
- Faster Random;
- More Culling Extra;
- Connectivity by someaddon;
- Server Performance by someaddon;
- Structure Essentials by someaddon;
- Chunk Sending by someaddon;
- fix GPU memory leak by someaddon;
- Better Fps - Render Distance by someaddon;
- Limited Chunkloading - Chunk cleanup by someaddon;
- Better chunk loading by someaddon;
- Client Crafting by someaddon;
- Recipe Essentials by someaddon;
- Alternate Current;
- Log Begone;
- Nvidium;
- Smoke Supression.

I just want to know why because I believe you guys already did a research and it's not really easy to find the "why not to use" answers in the internet about these mods.

I know that: 
- DashLoader has compatibility problems;
- Better Beds and FastChests (only on github) is unnecessary because of Enhanced Block Entities;
- Ksyxis is unnecessary with Fastload (yet I've seen better performance with Ksyxis);
- Lazy Language Loader is unnecessary with Language Reload;
- Methane and Phosphor is unnecessary with Starlight.

What about taking a look in this mod Ruthenium, can be better than Dynamic FPS.

MemoryLeakFix got an update! Did you guys see? Maybe it works now and can be re-added?

**Comment by MenacingPerson** [comment]
LazyDFU and Starlight got obsoleted by 1.19.4 and 1.20.1 respectively. Krypton is useless on clients. C2ME used to be here but was removed due to instability. VMP is useful only on servers. Exordium leads to lower FPS in 1.20.1 in a lot of cases.

A lot of mods you listed are incompatible with Vanilla - those aren't used

Also some mods you listed here are only on curseforge, which is a problem

Nvidium is not present because it's not stable and only works on nvidia.

**Comment by cazpj** [comment]
Edited the original post to be more pleasing to read

**Comment by intergrav** [comment]
I'll give a reason why every single mod that you listed isn't shipped with Adrenaline :) For the mods that I said are "too niche" for Adrenaline, what I mean is that it does insignificant things and is not worth including an entire separate mod for. More mods is not always better - it causes us to take more time to update to newer versions, possibly cause incompatibility with content mods, and in most cases wont be beneficial for the user. Adrenaline is meant to optimize the game as much as possible while staying small.

> Good to know that this modpack doesn't want to add performance mods that aren't on modrinth, now I understand that it's not really a 100% complete performance modpack, but just a modrinth performance modpack.

This is not the case at all - it would be illegal for me to add someaddon's mods to Adrenaline for the reasoning I stated below. I am willing to add performance mods from CurseForge if it doesn't break licensing and the author is okay with it. Every other mod that you listed here is available on Modrinth and CurseForge, it's simply someaddon's mods that aren't.

- LazyDFU; Mojang optimized DFU so much that it's no longer needed after 1.19.4.
- Starlight; Mojang optimized the lighting engine and so Starlight is no longer needed on the client in 1.20.1 and after.
- Krypton; Nearly everything this mod does is server-side and it can cause some connections to completely break when used on the client. It is not known to improve performance in any way **on the client**.
- C2ME; Mod is in an alpha state and is experimental. This can lead to instability, or even in very rare cases, world corruption. It has very mixed opinions and I've seen people who think badly of it being included in a popular modpack like Adrenaline. It also doesn't have great mod compatibility, in many cases needed to be removed in modpacks that are built from Adrenaline.
- Fastload; No longer maintained and has various bugs that won't be fixed. It can make loading into servers even slower than vanilla. It also sometimes causes music/ambience from the main menu or a dimension to continue playing when loading into a world or switching dimensions. It's not really worth keeping overall.
- Language Reload; Very niche mod, that's all.
- Very Many Players; Server-side mod that's not proven to improve performance client-side. It's also only really noticable on server-side when there are multiple players online.
- Exordium; Does it's job by lowering the rate of UI rendering, and can be very noticable, especially on high refresh rate displays. It's also superseded by ImmediatelyFast and doesn't seem to improve anything with IF installed.
- FastQuit; Very niche mod.
- Noxesium; Nearly all optimizations and fixes are exclusive to the MCC Island server, and from the last time I checked it doesn't do too much otherwise. Maybe I could look into this eventually.
- FastAnim; Not proven to improve performance.
- ServerCore; Only improves performance server-side.
- Let Me Despawn; Could break vanilla parity and is once again a server-side mod.
- Clumps; Not much impact for a mod that could affect game mechanics.
- Faster Random; Not proven to improve performance.
- More Culling Extra; It does a very small amount of things that could break parity with vanilla rendering. It's mainly an example for use of the MoreCulling API, and isn't known to improve performance in most cases.
- Mods by someaddon; Nearly all of their mods are ARR and closed-source, and they seem to have a disliking towards Modrinth for some reason. In the past, we've asked why they've been so reluctant to upload to both platforms, CurseForge and Modrinth, and they had said that they'll use Modrinth once payouts are a thing on there. Fair enough. Months later, payouts are introduced on Modrinth, and then we ask again. They then said that there are "shady things" going on at Modrinth (without actually saying what happened) and that they'll use Modrinth when it's "better than CurseForge" (in what way?) A lot of their stuff is server-side and if you really want them then consider adding them manually. It would not be legal for me to add these mods to a Modrinth modpack because they're ARR.
  - Connectivity by someaddon
  - Server Performance by someaddon
  - Structure Essentials by someaddon
  - Chunk Sending by someaddon
  - fix GPU memory leak by someaddon
  - Better Fps - Render Distance by someaddon
  - Limited Chunkloading - Chunk cleanup by someaddon
  - Better chunk loading by someaddon
  - Client Crafting by someaddon
  - Recipe Essentials by someaddon
- Alternate Current; Does not have full vanilla parity, is a server-side mod, and only affects redstone.
- Log Begone; Utility mod that could possibly hide information from the user when uploading their logs to places and is not known to provide any performance impact.
- Nvidium; Very experimental mod (it could even result in system crashes in rare cases) which uses OpenGL mesh shaders and direct GPU memory to improve the game's rendering. It's exclusive to **turing-era** NVIDIA GPUs and overall is too unstable to include in Adrenaline. If you want it, I recommend adding it manually.
- Smoke Suppression. Very rare case to improve performance and probably doesn't do too much. It could require user configuration depending on what they're doing and there are other ways to improve performance in the same ways that this does, such as disabling smoke particles temporarily.

**Comment by Gaming32** [comment]
Additionally, FastQuit is in Additive.
